# Этап сборки
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем бинарник мигратора
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrator cmd/migrator/main.go

# Финальный легковесный образ
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/migrator .

ENTRYPOINT ["./migrator"]
