basePath: /
definitions:
  models.SubscriptionListDTO:
    properties:
      price:
        example: 400
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 09-2025
        type: string
    type: object
  models.SubscriptionListJSON:
    properties:
      price:
        example: 400
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 09-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  models.SubscriptionListToCostJSON:
    properties:
      end_date:
        example: 12-2025
        type: string
      service_name:
        example:
        - Netflix
        - Yandex Plus
        - Spotify
        items:
          type: string
        type: array
      start_date:
        example: 09-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API для сервиса подписок
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Subscription Service API
  version: "1.0"
paths:
  /subscription/users:
    get:
      description: Получает список подписок пользователя по userId из cookie
      parameters:
      - description: userId из cookie
        in: header
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SubscriptionListDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить список подписок
      tags:
      - subscriptions
  /subscriptions:
    delete:
      consumes:
      - application/json
      description: Удаление подписки по id из query-параметров
      parameters:
      - description: ID подписки для удаления
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Подписка успешно удалена
          schema:
            type: string
        "400":
          description: Некорректный id или не найдена подписка
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удалить подписку
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Добавляет подписку на сервис
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionListJSON'
      produces:
      - application/json
      responses:
        "200":
          description: Подписка успешно создана
          schema:
            type: string
        "400":
          description: Неправильный запрос или дубликат подписки
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Создать новую подписку
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет подписку по id переданному в query-параметрах
      parameters:
      - description: ID подписки для обновления
        in: query
        name: id
        required: true
        type: integer
      - description: Данные подписки для обновления
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionListJSON'
      produces:
      - application/json
      responses:
        "200":
          description: Подписка успешно обновлена
          schema:
            type: string
        "400":
          description: Неправильный запрос или невалидные данные
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscriptions/cost:
    post:
      consumes:
      - application/json
      description: Возвращает общую стоимость подписок на сервис в указанный период
      parameters:
      - description: Параметры периода и имени сервиса
        in: body
        name: periodCost
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionListToCostJSON'
      produces:
      - application/json
      responses:
        "200":
          description: Общая стоимость в поле result
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Ошибка в параметрах запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получить сумму стоимости по датам и имени сервиса
      tags:
      - subscriptions
schemes:
- http
- https
swagger: "2.0"
